#!/bin/bash

# shared dependencies
BASE_DEPS="contextlib2 numpy pyparsing pytz setuptools six wheel zipp"
REQUESTS_DEPS="chardet certifi idna urllib3 requests"
# ordered package dependencies (some dependencies shared from BASE_DEPS)
MATPLOTLIB_DEPS="cycler kiwisolver Pillow python_dateutil matplotlib"
PYTESTCOV_DEPS="attrs iniconfig coverage py typing-extensions importlib-metadata toml packaging pluggy pytest pytest-cov"
LMPY_DEPS="Rtree DendroPy"
LMTEST_DEPS="Lifemapper_Client_Library Lifemapper_Testing_Library"
OTHER_DEPS="biotaphypy Cython idigbio lmpy"
1